To use PARCELS or the PYTHON script for plotting NEMO diagnostics, first build
the python environment, or check out the built executables from DockerHub.

[Set up Python environment](https://github.com/NOC-MSM/Belize_workshop/wiki/D-0:-SETUP-PYTHON-ENV)

*At present (20 Sept) the python environment is about 3Gb...*



PYTHON DIAGNOSTICS OF NEMO SURFACE FIELDS DEMONSTRATION
=======================================================

Ensure all your data files are in this directory::

  cp <STUFF> $HOME/Belize_workshop/PYTHON_TOOLS/PYTHON_DIAGNOSTICS/.

Run docker instance::

  docker run -v /Users/jeff/Belize_workshop/PYTHON_TOOLS:/PYTHON_TOOLS -t -i blz_python /bin/bash
  cd /PYTHON_TOOLS/PYTHON_DIAGNOSTICS/

Then you can start python, and hopefully do things::

  python NEMO_surface_var_diag.py BLZ
